- hosts: all
  tasks:
    - name: Install apache2 for Debian
      package:
        name: apache2
      when: ansible_os_family == "Debian"
    
    - name: restart apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
      
    - name: Install apache2 for Centos
      package:
        name: httpd
      when: ansible_os_family == "RedHat"
      
    - name: restart httpd service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"
    
    - name: Install git
      package:
        name: git
        
    - name: Git checkout
      git:
        repo: 'https://github.com/cloudacademy/static-website-example'
        dest: /var/www/html/cloudacademy  
